---
title: "Basic R"
output:
  html_notebook: default
---

```{r setup}
library(tidyverse)
```

## Dataframes

From R help: A data frame is a **list** of variables of the **same number of rows** with unique row names, given class `"data.frame"`

```{r good-df}
# empty vectors
n <- 5
x <- vector(n, mode = "logical")
y <- vector(n, mode = "character")
z <- vector(n, mode = "integer")
zx <- vector(n, mode = "double")
df1 <- data.frame(var_a = x, var_b = y, var_c = z, var_d = zx)
dim(df1)
#View(df1)
```

```{r bad-df, eval=FALSE}
# not a good idea
zx <- vector(4, mode = "double")
df2 <- data.frame(var_a = x, var_b = y, var_c = z, var_d = zx)
```

Converted to `tibble`

```{r tib1}
tib1 <- tibble(df1)
tib1
tib1[,2]
```

More interesting dataframe.

```{r interesting-df}
# 42 Answer to the Ultimate Question of Life, the Universe, and Everything,
set.seed(42)
x <- sample(c(TRUE, FALSE), size = 5, replace = TRUE, prob = c(0.75, 0.25))
y <- sample(LETTERS, size = 5, replace = TRUE)
z <- seq(from = 2, to = 14, by = 3)
zx <- runif(n = 5, min = 1, max = 2)
df2 <- data.frame(var_a = x, var_b = y, var_c = z, var_d = zx)
# print df1 in Console
```

```{r}
tib2 <- tibble(df2)
```

Pick values

```{r}
tib2[3,2]
tib2[2,]
tib2[["var_b"]]
tib2["var_b"]
# vector
class(tib2[["var_b"]])
# data frame with 1 col and 4 rows
class(tib2["var_b"])
```

## Matrix

```{r mat_basic}
matrix(1:10, nrow=3, ncol=4)
matrix(1:6, nrow=3, ncol=4)
matrix(1:4, nrow=3, ncol=4)
matrix(1:7, nrow=3, ncol=4)
matrix(1:7, nrow=3, ncol=4, byrow=TRUE)
letters
letters[5:12]
matrix(letters[5:12], nrow=3, ncol=4)
matrix(c(TRUE, FALSE, FALSE), nrow=3, ncol=4)
matrix(c(TRUE, FALSE, FALSE,TRUE), nrow=3, ncol=4)
matrix(letters[10:12], nrow=3, ncol=4)
matrix(letters[10:12], nrow=3, ncol=4, byrow = TRUE)
m <- matrix(letters[10:12], nrow=3, ncol=4, byrow = TRUE)
```

Get values out of matrices.

```{r get_mat_val}
m[2,]
m[2,3]
#m[c(1,4),]
m[c(1,3),]
m[,c(1,3)]
m[,-c(1,3)]
m[-1,-c(1,3)]
m[c(2,3), c(2,3)]
```

Naming rows and columns.

```{r dimnames_mat}
m <- matrix(letters[10:12], nrow=3, ncol=4, byrow = TRUE, dimnames=list(paste("rekke", 1:3, sep="1"), paste("kol", 1:4, sep="")))

m <- matrix(letters[10:12], nrow=3, ncol=4, byrow = TRUE, dimnames=list(paste("rekke", 1:3, sep="_"), paste("kol", 1:4, sep="")))

m <- matrix(letters[10:12], nrow=3, ncol=4, byrow = TRUE, dimnames=list(paste("rekke", 1:3, sep="_"), paste("kol", LETTERS[1:4], sep="")))

m <- matrix(letters[10:12], nrow=3, ncol=4, byrow = TRUE, dimnames=list(paste(c("rekke", "rad"), 1:3, sep="_"), paste("kol", LETTERS[1:4], sep="")))

# neste feil dim
#m <- matrix(letters[10:12], nrow=6, ncol=4, byrow = TRUE, dimnames=list(paste(c("rekke", "rad"), 1:3, sep="_"), paste("kol", LETTERS[1:4], sep="")))
# riktig dim
m <- matrix(letters[10:12], nrow=5, ncol=4, byrow = TRUE, dimnames=list(paste(c("rekke", "rad"), 1:5, sep="_"), paste("kol", LETTERS[1:4], sep="")))
```

```{r}
mat1 <- matrix(1:6, nrow=3, ncol=4, byrow=TRUE)
mat1[1,3] <- 13
mat1
```

## Functions for text

Difference `paste`, `cat` and `print`

```{r}
paste(1:3, "text", sep = "-")
cat(1:3, "text", sep = "-")
print(c(1:3, "text"))
```

```{r}
paste(1:3, "text", sep = "\n")
cat(1:3, "text", sep = "\n")
```

```{r}
#siste
```
